version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # AMQP port
      - "15672:15672"  # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - microservices-network

  # Opcional: SQL Server para produção
  # sqlserver:
  #   image: mcr.microsoft.com/mssql/server:2022-latest
  #   container_name: sqlserver
  #   ports:
  #     - "1433:1433"
  #   environment:
  #     ACCEPT_EULA: Y
  #     SA_PASSWORD: "YourStrong@Passw0rd"
  #   volumes:
  #     - sqlserver_data:/var/opt/mssql
  #   networks:
  #     - microservices-network

volumes:
  rabbitmq_data:
  # sqlserver_data:

networks:
  microservices-network:
    driver: bridge


